{{- if and .Values.database.enabled .Values.database.enableSuperuserAccess .Values.database.superuser.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pressao-api.cnpg.superuserSecretName" . }}
  labels:
    {{- include "pressao-api.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.superuser.username | quote }}
  password: {{ .Values.database.superuser.password | quote }}
{{- end }}
