{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pressao-api.secretName" . }}
  labels:
    {{- include "pressao-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.KEYCLOAK_CLIENT_SECRET | quote }}
  SENDGRID_API_KEY: {{ .Values.secrets.SENDGRID_API_KEY | quote }}
  SENDGRID_WEBHOOK_VERIFICATION_KEY: {{ .Values.secrets.SENDGRID_WEBHOOK_VERIFICATION_KEY | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.TWILIO_ACCOUNT_SID | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.TWILIO_AUTH_TOKEN | quote }}
  {{- if and (not .Values.database.enabled) (not .Values.database.existingSecret) }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  {{- end }}
{{- end }}
