"""add activist info

Revision ID: 1e368bb683a5
Revises: b0f35b54c2c5
Create Date: 2026-08-08 23:26:55.807175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e368bb683a5'
down_revision: Union[str, Sequence[str], None] = 'b0f35b54c2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acoes', sa.Column('ativista_nome', sa.String(length=200), nullable=True))
    op.add_column('acoes', sa.Column('ativista_email', sa.String(length=200), nullable=True))
    op.add_column('acoes', sa.Column('ativista_telefone', sa.String(length=20), nullable=True))
    op.add_column('acoes', sa.Column('anonimo', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    op.create_index(op.f('ix_acoes_ativista_email'), 'acoes', ['ativista_email'], unique=False)
    op.create_index(op.f('ix_acoes_ativista_telefone'), 'acoes', ['ativista_telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acoes_ativista_telefone'), table_name='acoes')
    op.drop_index(op.f('ix_acoes_ativista_email'), table_name='acoes')
    op.drop_column('acoes', 'anonimo')
    op.drop_column('acoes', 'ativista_telefone')
    op.drop_column('acoes', 'ativista_email')
    op.drop_column('acoes', 'ativista_nome')
    # ### end Alembic commands ###
