"""Add campanhas and alvos tables

Revision ID: 907c99c7ce8c
Revises: c27ae51dbfb1
Create Date: 2026-08-09 10:30:12.148018

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907c99c7ce8c"
down_revision: str | Sequence[str] | None = "c27ae51dbfb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campanhas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("dominios_permitidos", sa.JSON(), nullable=True),
        sa.Column("ativa", sa.Boolean(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campanhas_nome"), "campanhas", ["nome"], unique=False)
    op.create_table(
        "alvos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("contato", sa.String(length=200), nullable=False),
        sa.Column(
            "tipo_contato",
            sa.Enum("EMAIL", "TELEFONE", "WHATSAPP", "INSTAGRAM", name="tipocontato"),
            nullable=False,
        ),
        sa.Column("campanha_id", sa.UUID(), nullable=False),
        sa.Column("metadados", sa.JSON(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["campanha_id"], ["campanhas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alvos_contato"), "alvos", ["contato"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alvos_contato"), table_name="alvos")
    op.drop_table("alvos")
    op.drop_index(op.f("ix_campanhas_nome"), table_name="campanhas")
    op.drop_table("campanhas")
    # ### end Alembic commands ###
