"""Create acoes table

Revision ID: b0f35b54c2c5
Revises: 
Create Date: 2026-08-05 23:39:42.222262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f35b54c2c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativista_id', sa.String(length=100), nullable=False),
    sa.Column('campanha_id', sa.UUID(), nullable=False),
    sa.Column('alvo_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSANDO', 'AGUARDANDO_ACAO_HUMANA', 'CONCLUIDA', 'FALHA', name='status_acao'), nullable=False),
    sa.Column('proximo_passo_tipo', sa.Enum('WEBHOOK_AGUARDAR', 'REDIRECIONAR_LINK', 'EXIBIR_TEXTO_E_ABRIR_PERFIL', 'FINALIZADO', name='proximo_passo_tipo'), nullable=True),
    sa.Column('proximo_passo_instrucao', sa.String(length=500), nullable=True),
    sa.Column('proximo_passo_dados', sa.JSON(), nullable=True),
    sa.Column('metrica_qualidade', sa.Enum('suspeita', 'alta', 'media', 'baixa', name='metrica_qualidade'), nullable=True),
    sa.Column('tempo_resposta_seg', sa.Integer(), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acoes_alvo_id'), 'acoes', ['alvo_id'], unique=False)
    op.create_index(op.f('ix_acoes_ativista_id'), 'acoes', ['ativista_id'], unique=False)
    op.create_index(op.f('ix_acoes_campanha_id'), 'acoes', ['campanha_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acoes_campanha_id'), table_name='acoes')
    op.drop_index(op.f('ix_acoes_ativista_id'), table_name='acoes')
    op.drop_index(op.f('ix_acoes_alvo_id'), table_name='acoes')
    op.drop_table('acoes')
    # ### end Alembic commands ###
