"""change activist_id to nullable

Revision ID: c27ae51dbfb1
Revises: 1e368bb683a5
Create Date: 2026-08-08 23:32:16.746399

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c27ae51dbfb1"
down_revision: str | Sequence[str] | None = "1e368bb683a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("acoes", "ativista_id", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("acoes", "ativista_id", existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###
